Algoritmo "lista_Emprego'
//  
//  

Var
 horario:inteiro
 salario:real
 cont:inteiro


Inicio


para cont de 1 ate 10 passo 2  faca
     escreva ( cont )
     
     escreva ( " - digite o salario : " )
     leia ( salario)
     se ( salario <= 2000 ) entao
           escreval ( "candidato selecionando para primeira fase" )

             senao
                   escreval ( "candidato nao preencheu os resquisitos da vaga" )
                   
                   fimse
      fimpara

Fimalgoritmo