Algoritmo "operadores_relacionais"
//  
//  

                                       // OPERADOR ,OPERAÇÃO
                                       
                                       //     =     IGUAL A
                                       //    <>     DIFERENTE DE
                                       //     >     MAIOR QUE
                                       //     <     MENOR QUE
                                       //     >=    MAIOR OU IGUAL A
                                       //     <=    MENOR OU IGUAL A



Var
 A: INTEIRO
 
 B: INTEIRO
 
 RESULTADO: LOGICO


Inicio
 A <- 10
 B <- 6

 RESULTADO <- A >= B
 
 ESCREVAL ("TESTE COM OPERADOR RELACIONAL maior ou igual a  : ", A, " > " , B, "?", RESULTADO)


Fimalgoritmo